### PR TITLE
Make powerpc compatible

### PR DESCRIPTION
**Pull request by ghost**
Add conditional compilation to enable cross-compiling to powerpc architecture.

### CODE REVIEW

**Comment by rodrimati1992** [comment]
Thanks.
So do you want a patch release today/tomorrow?

**Comment by ghost** [comment]
Hi! Thanks for the quick review.

Yes a patch release would be great, thank you!

**Comment by rodrimati1992** [comment]
Do you have a reference for powerpc not supporting byte atomics?I tried to find some information about the supported size of atomic operations, but couldn't find anything.

**Comment by ghost** [comment]
Hi.

From here: https://doc.rust-lang.org/std/sync/atomic/index.html

"PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types."

**Comment by rodrimati1992** [comment]
Ok,made [the patch release](https://crates.io/crates/core_extensions/0.1.17).

**Pull request merged**
